name: Hardhat Tests

on: [push]

jobs:
  test:
    name: Run Hardhat Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
        name: Check out repository code

      # Set up Node.js environment
      - uses: actions/setup-node@v2
        name: Set up Node.js
        with:
          node-version: '20' # Set this to your Node.js version

      # Create .env file and populate it with secrets
      - name: Create env file
        run: |
          touch .env
          echo "ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}" >> .env
          echo "ALCHEMY_URL=${{ secrets.ALCHEMY_URL }}" >> .env
          echo "WALLET_PK=${{ secrets.WALLET_PK }}" >> .env
          cat .env
        working-directory: ./blockchain

      # Install dependencies in the blockchain directory
      - name: Install dependencies
        run: yarn install
        working-directory: ./blockchain

      # Run Hardhat tests
      - name: Run Hardhat Test
        run: yarn run hardhat test --network hardhat
        working-directory: ./blockchain
