name: Hardhat Tests

on: [push]

jobs:
  test:
    name: Run Hardhat Tests
    env: # Or as an environment variable
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      ALCHEMY_URL: ${{ secrets.ALCHEMY_URL }}
      WALLET_PK: ${{ secrets.WALLET_PK }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    # Setup Node.js environment
    - uses: actions/setup-node@v2
      name: Set up Node.js
      with:
        node-version: '20' # Set this to your Node.js version

    # Install dependencies in the blockchain directory
    - name: Install dependencies
      run: |
        cd blockchain
        yarn install

    # Run Hardhat tests
    - name: Run Hardhat Test
      run: |
        cd blockchain
        yarn run hardhat test --network localhost
